name: Share data between jobs

on: [workflow_dispatch]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework1.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework1
          path: math-homework1.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: homework1
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework1.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v4
        with:
          name: homework1
          path: math-homework1.txt
